FROM php:8.1.3RC1-apache-buster


# Clear cache
 RUN apt-get clean && rm -rf /var/lib/apt/lists/*

 RUN apt-get update && apt-get install -y curl

RUN apt-get update -y && apt-get upgrade -y

RUN apt-get install -y  unzip 

# Install Git
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y git
# Install MySQL
RUN docker-php-ext-install  mysqli pdo pdo_mysql && a2enmod rewrite

RUN docker-php-ext-configure mysqli \
        && docker-php-ext-install -j$(nproc) mysqli




# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer 

COPY --from=composer/composer:latest-bin /composer /usr/bin/composer


RUN curl -sS https://get.symfony.com/cli/installer | bash


# Install Xdebug
RUN pecl install xdebug apcu\
    && docker-php-ext-enable xdebug \
    && echo "xdebug.mode=debug" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
     && echo "xdebug.client_host = host.docker.internal" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

    # Set working directory
    WORKDIR /var/www/html

    #grant permissin using
    #chown -R hp ./directory
    #install symfony using composer 6.4 
    #install test suite composer require --dev symfony/test-pack
